/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    UiAdvanceFilter: typeof import('./src/components/UiAdvanceFilter.vue')['default']
    UiCard: typeof import('./src/components/UiCard.vue')['default']
    UiCardHeader: typeof import('./src/components/UiCardHeader.vue')['default']
    UiConfirmDialog: typeof import('./src/components/UiConfirmDialog.vue')['default']
    UiFormGroup: typeof import('./src/components/UiFormGroup.vue')['default']
    UiPercentage: typeof import('./src/components/UiPercentage.vue')['default']
    UiSearch: typeof import('./src/components/UiSearch.vue')['default']
    UiSwitch: typeof import('./src/components/UiSwitch.vue')['default']
    UiToast: typeof import('./src/components/UiToast.vue')['default']
    UiWrapIcon: typeof import('./src/components/UiWrapIcon.vue')['default']
  }
}
